### ISSUE TITLE
can't poll inverter

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [basking-in-the-sun2000/solar-logger#42]
Hello,
I tryed to run the main.py after checking that the connection is fine but I'm not able to see any data in response: I always receive 

```
anto@raspberrypi:~/solar-logger-master $ python3 main.py 
mailing not setup
starting
Thu May 26 23:57:54 2022
Loaded: Huawei
statring setup
opening modbus
192.168.10.5
opening db
setting db
setting params
main 1 error: list index out of range
main 2 error: list index out of range
SELECT min("Insulation") as "Insulation" FROM "Huawei_info" WHERE time >= 1653429600000000000 and time <= 1653516000000000000 and Insulation > 0
starting
in forecast
Thu May 26 23:57:56 2022
8
20
Fri May 27 00:22:56 2022
next forecast Thu May 26 07:45:00 2022
forecast error: 'forecasts'
solcast off-line
Fri May 27 00:27:57 2022
8
20
Fri May 27 00:52:57 2022
next forecast Thu May 26 07:45:00 2022
loop
mdobus read_registers error: Modbus Error: [Connection] ModbusTcpClient(192.168.10.5:502): Connection unexpectedly closed 0.000114 seconds into read of 8 bytes without response from unit before it closed connection
do_map error: 'int' object has no attribute 'isError'
trying to recover Model 1
mdobus read_registers error: Modbus Error: [Connection] ModbusTcpClient(192.168.10.5:502): Connection unexpectedly closed 1.762673 seconds into read of 8 bytes without response from unit before it closed connection
do_map error: 'int' object has no attribute 'isError'
trying to recover Model 2
read register error Model 3
read register error Model 4
Thu May 26 23:58:20 2022 Model
map looping
mdobus read_registers error: Modbus Error: [Connection] ModbusTcpClient(192.168.10.5:502): Connection unexpectedly closed 2.264459 seconds into unbounded read without response from unit before it closed connection
do_map error: 'int' object has no attribute 'isError'
trying to recover Model 1
mdobus read_registers error: Modbus Error: [Connection] ModbusTcpClient(192.168.10.5:502): Connection unexpectedly closed 2.265290 seconds into unbounded read without response from unit before it closed connection

```

Have you any suggestion?
I also tryed to retreive data with external clients but I'm never able to see any output
Thanks in advance!

_Originally posted by @2022Anto in https://github.com/basking-in-the-sun2000/solar-logger/discussions/37#discussioncomment-2827832_

**Comment by basking-in-the-sun2000** [comment]
sounds like you are having issues connecting to your inverter. The ip you provided seems to be valid, but it isn't connecting to your inverter to poll it

**Comment by andysu** [comment]
1. ping 192.168.10.5
2. telnet 192.168.10.5 502
3. try to read any register (32001 or 40120)  by python script like this

`
from pymodbus.client.sync import ModbusTcpClient as ModbusClient
import logging
FORMAT = ('%(asctime)-15s %(threadName)-15s '
          '%(levelname)-8s %(module)-15s:%(lineno)-8s %(message)s')
logging.basicConfig(format=FORMAT)
log = logging.getLogger()
log.setLevel(logging.DEBUG)

UNIT = 0x00
from time import sleep

def execute_extended_requests():
    client = ModbusClient('192.168.10.5', port=502
    client.connect()
    sleep(1)
    rr=client.read_holding_registers(40120,1)
    log.debug(rr.registers)
     client.close()

if __name__ == "__main__":
    execute_extended_requests()

`

**Comment by verisgit** [comment]
Are you on the inverters Wifi network? Sun2000 doesn't allow tcp connections from outside of its internal wifi network. So even though the inverter may appear on your lan as 192.168.1.200 for example you can't connect to modbus on that IP. You will need to either bridge the connection by running a RPI or similar to bridge the wifi connection to your main LAN via google Ethernet or buy a SDongleA-05 which plugs into the Sun2000 and exposes the modbus on your main LAN. Personally I use an RPI connected to the inverter via wifi and then I connect to the RPI via Ethernet - works well. You also need to set the inverter to allow modbus over tcp on all IPs, I've never seen restricted mode actually work.

**Comment by 2022Anto** [comment]
I tried with external client and I'm able to open the connection succesfully as visible in the attached picture
![Huawei-connected](https://user-images.githubusercontent.com/104466180/170651671-2e071d1a-8002-45b3-808d-bdcb8a9367f8.JPG)

If I try to add any register (eg. 30000 model) the connection goes lost
![Huawei-not_connected](https://user-images.githubusercontent.com/104466180/170652074-07f5fa72-4399-478a-94bf-af6e4dd6e9f0.JPG)

I wander if the register numbers in Huawei inverter have been changed or if some offset has to be applied but from the docs  I have it doest't seems so
[Da_Huawei_SDongleA V100R001C00 MODBUS Interface Definitions.pdf](https://github.com/basking-in-the-sun2000/solar-logger/files/8784789/Da_Huawei_SDongleA.V100R001C00.MODBUS.Interface.Definitions.pdf)
[Da_Huawei_Solar Inverter Modbus Interface Definitions.pdf](https://github.com/basking-in-the-sun2000/solar-logger/files/8784791/Da_Huawei_Solar.Inverter.Modbus.Interface.Definitions.pdf)



> Are you on the inverters Wifi network? Sun2000 doesn't allow tcp connections from outside of its internal wifi network. So even though the inverter may appear on your lan as 192.168.1.200 for example you can't connect to modbus on that IP. You will need to either bridge the connection by running a RPI or similar to bridge the wifi connection to your main LAN via google Ethernet or buy a SDongleA-05 which plugs into the Sun2000 and exposes the modbus on your main LAN. Personally I use an RPI connected to the inverter via wifi and then I connect to the RPI via Ethernet - works well. You also need to set the inverter to allow modbus over tcp on all IPs, I've never seen restricted mode actually work.

I'm using the SDongle on the same LAN of RPI. I checked on the inverter config but I can only see one place to enable modbus and no options to enable modbus over all IPs. thanks!

**Comment by 2022Anto** [comment]
> 

anto@raspberrypi:~/solar-logger-master $ ping 192.168.10.5
PING 192.168.10.5 (192.168.10.5) 56(84) bytes of data.
64 bytes from 192.168.10.5: icmp_seq=1 ttl=255 time=0.424 ms
64 bytes from 192.168.10.5: icmp_seq=2 ttl=255 time=0.354 ms
64 bytes from 192.168.10.5: icmp_seq=3 ttl=255 time=0.357 ms
^C
--- 192.168.10.5 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2115ms
rtt min/avg/max/mdev = 0.354/0.378/0.424/0.032 ms

anto@raspberrypi:~/solar-logger-master $ telnet 192.168.10.5 502
Trying 192.168.10.5...
Connected to 192.168.10.5.
Escape character is '^]'.
Connection closed by foreign host.

anto@raspberrypi:~/solar-logger-master $ python3 test_regist.py 
2022-05-27 14:51:02,772 MainThread      DEBUG    sync           :215      Connection to Modbus server established. Socket ('192.168.10.43', 55061)
2022-05-27 14:51:03,774 MainThread      DEBUG    transaction    :139      Current transaction state - IDLE
2022-05-27 14:51:03,774 MainThread      DEBUG    transaction    :144      Running transaction 1
2022-05-27 14:51:03,775 MainThread      DEBUG    transaction    :273      SEND: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x9c 0xb8 0x0 0x1
2022-05-27 14:51:03,775 MainThread      DEBUG    sync           :76       New Transaction state 'SENDING'
2022-05-27 14:51:03,776 MainThread      DEBUG    transaction    :287      Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2022-05-27 14:51:06,780 MainThread      DEBUG    transaction    :303      Transaction failed. (Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)) 
2022-05-27 14:51:06,781 MainThread      DEBUG    socket_framer  :147      Processing: 
2022-05-27 14:51:06,781 MainThread      DEBUG    transaction    :465      Getting transaction 1
2022-05-27 14:51:06,781 MainThread      DEBUG    transaction    :224      Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'
Traceback (most recent call last):
  File "/home/anto/solar-logger-master/test_regist.py", line 22, in <module>
    execute_extended_requests()
  File "/home/anto/solar-logger-master/test_regist.py", line 18, in execute_extended_requests
    log.debug(rr.registers)
AttributeError: 'ModbusIOException' object has no attribute 'registers'

anto@raspberrypi:~/solar-logger-master $ python3 test_regist.py 
2022-05-27 14:51:47,373 MainThread      DEBUG    sync           :215      Connection to Modbus server established. Socket ('192.168.10.43', 46859)
2022-05-27 14:51:48,376 MainThread      DEBUG    transaction    :139      Current transaction state - IDLE
2022-05-27 14:51:48,376 MainThread      DEBUG    transaction    :144      Running transaction 1
2022-05-27 14:51:48,376 MainThread      DEBUG    transaction    :273      SEND: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x7d 0x1 0x0 0x1
2022-05-27 14:51:48,377 MainThread      DEBUG    sync           :76       New Transaction state 'SENDING'
2022-05-27 14:51:48,377 MainThread      DEBUG    transaction    :287      Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2022-05-27 14:51:51,381 MainThread      DEBUG    transaction    :303      Transaction failed. (Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)) 
2022-05-27 14:51:51,381 MainThread      DEBUG    socket_framer  :147      Processing: 
2022-05-27 14:51:51,382 MainThread      DEBUG    transaction    :465      Getting transaction 1
2022-05-27 14:51:51,383 MainThread      DEBUG    transaction    :224      Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'
Traceback (most recent call last):
  File "/home/anto/solar-logger-master/test_regist.py", line 22, in <module>
    execute_extended_requests()
  File "/home/anto/solar-logger-master/test_regist.py", line 18, in execute_extended_requests
    log.debug(rr.registers)
AttributeError: 'ModbusIOException' object has no attribute 'registers'
anto@raspberrypi:~/solar-logger-master $ python3 test_regist.py 
2022-05-27 16:27:25,059 MainThread      DEBUG    sync           :215      Connection to Modbus server established. Socket ('192.168.10.43', 58975)
2022-05-27 16:27:26,061 MainThread      DEBUG    transaction    :139      Current transaction state - IDLE
2022-05-27 16:27:26,062 MainThread      DEBUG    transaction    :144      Running transaction 1
2022-05-27 16:27:26,062 MainThread      DEBUG    transaction    :273      SEND: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x7d 0x1 0x0 0x1
2022-05-27 16:27:26,062 MainThread      DEBUG    sync           :76       New Transaction state 'SENDING'
2022-05-27 16:27:26,063 MainThread      DEBUG    transaction    :287      Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2022-05-27 16:27:29,067 MainThread      DEBUG    transaction    :303      Transaction failed. (Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)) 
2022-05-27 16:27:29,067 MainThread      DEBUG    socket_framer  :147      Processing: 
2022-05-27 16:27:29,068 MainThread      DEBUG    transaction    :465      Getting transaction 1
2022-05-27 16:27:29,068 MainThread      DEBUG    transaction    :224      Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'
Traceback (most recent call last):
  File "/home/anto/solar-logger-master/test_regist.py", line 22, in <module>
    execute_extended_requests()
  File "/home/anto/solar-logger-master/test_regist.py", line 18, in execute_extended_requests
    log.debug(rr.registers)
AttributeError: 'ModbusIOException' object has no attribute 'registers'

**Comment by basking-in-the-sun2000** [comment]
If you think it is that the registers changed, you can try to scan the space. scanner.py allows you to do that.

However, don't think that is the problem. Supposedly the dongle should be slave id 1, but have you tried 0?

Seems that port 502 is open. Huawei has started blocking it on some releases. They are also using port 6607.

Also take a look at these
https://forum.huawei.com/enterprise/en/modbus-tcp-guide/thread/789585-100027
https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-the-inverter

If none of these work, then you might need to contact support, since your inverter seems to be blocking connections

**Comment by andysu** [comment]
seems to be wrong unit
try to change str
rr=client.read_holding_registers(40120,1)
by
rr=client.read_holding_registers(40120,1,unit=1)
or unit=1,2,3,4,....

**Comment by andysu** [comment]
> However, don't think that is the problem. Supposedly the dongle should be slave id 1, but have you tried 0?
in modbusTCP unit=0x00 (as in sdongle docs)

**Comment by 2022Anto** [comment]
Thanks for your feedback!
I tryed scanner.py with config.py configured with 0x00, 0x01 and 0x02 on both 502 and 6607 on Sdongle LAN but I never receive any reponse. 
```
anto@raspberrypi:~/solar-logger-master $ vi config.py 
anto@raspberrypi:~/solar-logger-master $ ./scanner.py 
openning
Sun, 29 May 2022 22:27:45
Traceback (most recent call last):
  File "/home/anto/solar-logger-master/./scanner.py", line 68, in <module>
    result = read_holding(client, UnitID, i, 1)
  File "/home/anto/solar-logger-master/./scanner.py", line 37, in read_holding
    result = client.read_holding_registers(i, nb, unit=UnitID)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 109, in execute
    return self.transaction.execute(request)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/transaction.py", line 174, in execute
    response, last_exception = self._transact(
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/transaction.py", line 294, in _transact
    result = self._recv(response_length, full)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/transaction.py", line 326, in _recv
    read_min = self.client.framer.recvPacket(min_size)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/framer/__init__.py", line 49, in recvPacket
    return self.client.recv(size)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 89, in recv
    return self._recv(size)
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 297, in _recv
    return self._handle_abrupt_socket_close(
  File "/home/anto/.local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 342, in _handle_abrupt_socket_close
    raise ConnectionException(msg)
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] ModbusTcpClient(192.168.10.5:502): Connection unexpectedly closed 0.825374 seconds into read of 8 bytes without response from unit before it closed connection
anto@raspberrypi:~/solar-logger-master $ 

```
On both WIFI inverter and dongle the ports 502 and 6607 are not opened. 
I opened a ticket on eu_support Huawey (I'm in Italy) and waiting for support. I'll let you know!

**Comment by basking-in-the-sun2000** [comment]
scanner.py was something I used to figure some of the registers. It is a bit clunky, and haven't updated to reflect some of the changes. For instance, it doesn't know some config settings like UnitID.

To try the value from the config.py file, you can change line 55 to **UnitID = config.slave**

Hopefully, Huawei can help you get your inverter talking

**Comment by andysu** [comment]
some additional info about huawei suport:
eu_inverter_support@huawei.com
at this address I communicated (fruitfully) with support. Also tell them the serial of your inverter
You can also ask questions on the forum.
forum.huawei.com basking-in-the-sun2000 is there

**Comment by andysu** [comment]
> I bask where the sun2000 shines
> 
> Glad they helped. I always forget the sn.
> 
> So did you got the logger talking to your inverter?

not yet
i have RaspPi 2 connected to inverters
but grafana only 64bit (RPi2 - x32)
im working on this. As solution - ssh serial proxy

**Comment by basking-in-the-sun2000** [comment]
grafana has a armhf version, which I think should work on a rpi 2. However, you might have trouble with the ram, don't know if you might have enough. I'm using 1.5 GB on a rpi 4

**Comment by andysu** [comment]
> grafana has a armhf version
my mistake, thnx!

**Comment by andysu** [comment]
another offer
influxDB+rabbit+telegraph+grafana can be moved to a cloud server (oracle free tier)
(i have oracle free tier server with all and 12 clients from inverters)
locally leave only the MQTT client.

**Comment by andysu** [comment]
> have you ever thought to install on a docker this project running on NAS like qnap?

we need to create 2 docker images 
1st  - local (all components+ mqtt client)
2st - remote mqtt server with (or without grafana) - influxdb+rabbit+telgraf+grafana+nginx+certbot(for ssl)
case with remote grafana may start on many-many devices. Only thing - add accumulate logs without internet and send them when internet comes.

**Comment by 2022Anto** [comment]
> > have you ever thought to install on a docker this project running on NAS like qnap?
> 
> we need to create 2 docker images 1st - local (all components+ mqtt client) 2st - remote mqtt server with (or without grafana) - influxdb+rabbit+telgraf+grafana+nginx+certbot(for ssl) case with remote grafana may start on many-many devices. Only thing - add accumulate logs without internet and send them when internet comes.

you mean Modbus not Mqtt

**Comment by 2022Anto** [comment]
I would prefer not to use FusionSolar remote server. 
My intention was to store the data into a NAS instead of on raspberry for obvius reason of storage. It's true that I could use Influd db installed on NAS and the polling script on raspberry but if I could have all installed on NAS would have more sense.
